<!-- BEGIN HAPPY CLIENT SECTION -->
<div class="section bg-light">
    <div class="container">
        <div class="section-heading">
            <div class="inner-border"></div>
            <h3>Newsletter</h3>
        </div><!-- /.section-heading -->

        <div class="col-sm-12 text-center">
            <h3><?php echo $message; ?></h3>
        </div>


    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END HAPPY CLIENT SECTION -->

<!-- BEGIN CLIENT LOGO SECTION -->
<div class="section">
    <div class="container">
        <?php echo $this->partial('partial/page/banners'); ?>
    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END CLIENT LOGO SECTION -->