<?php /* @var $page \CmsIr\Page\Model\Page */?>
<?php echo $this->partial('partial/breadcrumbs', array('breadcrumbs' => array('/' => 'Strona główna', $page->getName()))); ?>

<div class="container">
    <div class="row">
        <!-- BLOG LIST SECTION -->
        <div class="col-sm-12">
            <div class="section">
                <h4 class="light-font line-height-28 margin-top-50">
                    <?php echo $page->getContent() ?>
                </h4>
            </div>
        </div>
    </div>
</div>