<div id="owl-client-logo" class="owl-carousel client-logo">
    <?php if($banners): ?>
        <?php foreach($banners as $banner): ?>
            <?php
                $file = $banner->getFiles();
                $fileName = $file->getFilename();
            ?>
            <div class="item">
                <img src="/files/post/<?php echo $fileName; ?>" alt="Client logo">
            </div><!-- /.item -->
        <?php endforeach; ?>
    <?php endif; ?>
</div><!-- /#owl-client-logo -->