<div class="row">
    <!-- BEGIN SERVICES 4 COLUMN -->
    <div class="section">
        <div class="container">
            <div class="section-heading">
                <div class="inner-border"></div>
                <h3>Zorganizuj imprezę!</h3>
            </div><!-- /.section-heading -->
            <div class="row">
                <div class="col-sm-3 services-item text-center">
                    <h4>Pomysł</h4>
                    <i class="fa fa-flask icon-services-md bg-danger rounded"></i>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet
                        dolore magna aliquam erat volutpat.
                    </p>
                </div><!-- /.col-sm-3 -->
                <div class="col-sm-3 services-item text-center">
                    <h4>Termin</h4>
                    <i class="fa fa-apple icon-services-md bg-warning rounded"></i>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet
                        dolore magna aliquam erat volutpat.
                    </p>
                </div><!-- /.col-sm-3 -->
                <div class="col-sm-3 services-item text-center">
                    <h4>Budżet</h4>
                    <i class="fa fa-crosshairs icon-services-md bg-success rounded"></i>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet
                        dolore magna aliquam erat volutpat.
                    </p>
                </div><!-- /.col-sm-3 -->
                <div class="col-sm-3 services-item text-center">
                    <h4>Miejsce</h4>
                    <i class="fa fa-print icon-services-md bg-primary rounded"></i>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet
                        dolore magna aliquam erat volutpat.
                    </p>
                </div><!-- /.col-sm-3 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.section -->
    <!-- END SERVICES 4 COLUMN -->
</div><!-- /.row -->