<?php if ($this->pageCount): ?>
        <ul class="pagination info block-color separated">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('number' => $this->previous)); ?>">
                        <
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, array('number' => $page)); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('number' => $this->next)); ?>">
                        >
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >
                    </a>
                </li>
            <?php endif; ?>
        </ul>
<?php endif; ?>