<div class="footer light-color">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                Copyright &copy; 2014 <a href="<?php echo $this->url('home'); ?>">Twoja nazwa</a>
            </div><!-- /.col-sm-5 -->
            <div class="col-sm-7 text-right">
                <ul class="list-inline">
                    <li><a href="<?php echo $this->url('viewPage', array('slug' => 'regulamin')); ?>">Regulamin</a></li>
                    <li><a href="<?php echo $this->url('viewPage', array('slug' => 'polityka-prywatnosci')); ?>">Polityka prywatności</a></li>
                </ul>
            </div><!-- /.col-sm-7 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.footer -->