<div class="col-sm-6 col-md-4">
    <h4>KONTAKT</h4>
    <div class="media media-contact">
          <span class="pull-left">
                <i class="fa fa-map-marker media-object"></i>
          </span>
        <div class="media-body">
            <address>
                Twoja Nazwa.<br>
                Ulica 37/100<br>
                Miasto<br>
                (123) 456-7890
            </address>
        </div><!-- /.media-body -->
    </div><!-- /.media -->
    <div class="media media-contact">
          <span class="pull-left">
            <i class="fa fa-envelope media-object"></i>
          </span>
        <div class="media-body">
            <address>
                Imię i Nazwisko<br>
                <a href="mailto:#">first.last@example.com</a>
            </address>
        </div><!-- /.media-body -->
    </div><!-- /.media -->
</div><!-- /.col-sm-3 -->