<div class="col-sm-6 col-md-4">
    <h4>ZAPISZ SIĘ NA NEWSLETTER</h4>
    <p>
        Zostaw nam swój adres email, a będziesz otrzymywać
        wiadomości o nowych treściach na stronie!
    </p>
    <form role="form" id="newsletter">
        <div class="input-group subscribe">
            <input type="email" required class="form-control" name="email" placeholder="Wprowadź adres email">
            <span class="input-group-btn">
                 <button class="btn btn-info" type="submit" id="save-newsletter"><i class="fa fa-chevron-right"></i></button>
            </span>
        </div><!-- /input-group -->
    </form>
</div><!-- /.col-sm-3 -->